<?php

/**
 * @file
 * Modules hooks for the resource hints module.
 */

define('RESOURCE_HINTS_OUTPUT_LINK_HEADER', '0');
define('RESOURCE_HINTS_OUTPUT_LINK_ELEMENT', '1');
define('RESOURCE_HINTS_DNS_PREFETCH_HTTP_ONLY', '2');
define('RESOURCE_HINTS_DNS_PREFETCH_HTTP_AND_HTTPS', '3');
define('RESOURCE_HINTS_DNS_PREFETCH_DISABLED', '4');

/**
 * Implements hook_menu().
 */
function resource_hints_menu() {
  $items['admin/config/development/resources-hints'] = array(
    'title' => 'Resource Hints',
    'description' => 'Configure settings for resources hints.',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer resource hints'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('resource_hints_dns_prefetch_admin'),
    'file' => 'resource_hints.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function resource_hints_permission() {
  return array(
    'administer resource hints' => array(
      'title' => t('Administer Resource Hints'),
      'description' => t('Configure settings for resource hints'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function resource_hints_init() {

  $control = variable_get('resource_hints_dns_prefetch_protocol_control', RESOURCE_HINTS_DNS_PREFETCH_HTTP_ONLY);

  if ($control == RESOURCE_HINTS_DNS_PREFETCH_DISABLED) {
    drupal_add_html_head(
      array(
        '#tag' => 'meta',
        'http-equiv' => 'X-UA-Compatible',
        '#attributes' => array(
          'http-equiv' => 'x-dns-prefetch-control',
          'content' => 'off',
        ),
      ),
      __FUNCTION__
    );

    return;
  }
  else {
    drupal_add_html_head(
      array(
        '#tag' => 'meta',
        'http-equiv' => 'X-UA-Compatible',
        '#attributes' => array(
          'http-equiv' => 'x-dns-prefetch-control',
          'content' => 'on',
        ),
      ),
      __FUNCTION__
    );
  }

  $hint_types = array(
    'dns-prefetch' => 'resource_hints_dns_prefetch',
    'preconnect' => 'resource_hints_preconnect',
    'prefetch' => 'resource_hints_prefetch',
    'prerender' => 'resource_hints_prerender',
  );

  foreach ($hint_types as $rel => $variable_prefix) {
    foreach (explode(PHP_EOL, variable_get("{$variable_prefix}_resources", '')) as $value) {
      $value = drupal_strip_dangerous_protocols(trim($value));
      if ($value) {
        $output = variable_get("{$variable_prefix}_output", RESOURCE_HINTS_OUTPUT_LINK_HEADER);
        if ($output === RESOURCE_HINTS_OUTPUT_LINK_HEADER) {
          drupal_add_http_header('Link', "<{$value}>; rel={$rel}", TRUE);
        }
        else {
          drupal_add_html_head_link(
            array(
              'rel' => $rel,
              'href' => $value,
            ),
            FALSE
          );
        }
      }
    }
  }
}
