resource_hints.settings:
  type: config_object
  label: 'Resource Hints config'
  mapping:
    dns_prefetch_output:
      type: integer
      label: 'DNS Prefetch Output Type'
    dns_prefetch_resources:
      type: sequence
      label: 'DNS Prefetch Resources'
      sequence:
        type: string
        label: 'Resource'
    dns_prefetch_control:
      type: string
      label: 'DNS Protocol Control'
    preconnect_output:
      type: integer
      label: 'Preconnect Output Type'
    preconnect_resources:
      type: sequence
      label: 'Preconnect Resources'
      sequence:
        type: string
        label: 'Resource'
    prefetch_output:
      type: integer
      label: 'Prefetch Output Type'
    prefetch_resources:
      type: sequence
      label: 'Prefetch Resources'
      sequence:
        type: string
        label: 'Resource'
    prerender_output:
      type: integer
      label: 'Prerender Output Type'
    prerender_resources:
      type: sequence
      label: 'Prerender Resources'
      sequence:
        type: string
        label: 'Resource'
